name: Destroy All Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to destroy? e.g., dev, staging, prod"
        required: true
        default: "staging"
      tf_proj:
        description: "Which Terraform project to destroy? e.g., eks, rds, vpc"
        required: true
        default: "eks"
        type: "choice"
        options:
          - eks
          - rds
          - vpc

jobs:
  destroy-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize and Destroy
        run: |
          make init TF_PROJ=${{ inputs.tf_proj }} INFRA_ENV=${{ inputs.environment }}
          make destroy TF_PROJ=${{ inputs.tf_proj }} INFRA_ENV=${{ inputs.environment }}
